name: Build & Publish Release APK

on:
  push:
    tags:
      - '*'

jobs:
  Gradle:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: setup JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Make Gradle executable
      run: chmod +x ./gradlew
    - name: Build Release APK
      run: ./gradlew assembleDebug --stacktrace
    - name: Releasing using Hub
      uses: kyze8439690/action-release-releaseapk@master
      env:
       GITHUB_TOKEN: ${{ secrets.TOKEN_FOR_APK_RELEASE }}
       APP_FOLDER: app/build/outputs/apk/debug/app-debug.apk
