name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
      
  release:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: setup JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Make Gradle executable
      run: chmod +x ./gradlew
    - name: Build Release APK
      run: ./gradlew assembleDebug --stacktrace
    - name: Release APK
      uses: kyze8439690/action-release-releaseapk@1.0.0
      env:
       GITHUB_TOKEN: ${{ secrets.TOKEN_FOR_APK_RELEASE }}
       APP_FOLDER: app/build/outputs/apk/debug/app-debug.apk
