name: BuildRelease

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build APK
      run: bash ./gradlew assembleDebug --stacktrace
    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
         name: apk
         path: app/build/outputs/apk/debug/app-debug.apk
      
  release:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Download APK from build
      uses: actions/download-artifact@v1
      with:
        name: apk
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_FOR_APK_RELEASE }}
      with:
        tag_name: ${{ github.run_number }}
        release_name: ${{ github.event.repository.name }} v${{ github.run_number }}
    - name: Upload Release APK
      id: upload_release_asset
      uses: actions/upload-release-asset@v1.0.1
      env:
       GITHUB_TOKEN: ${{ secrets.TOKEN_FOR_APK_RELEASE }}
       APP_FOLDER: app/build/outputs/apk/debug/app-debug.apk
